# Generated by Django 3.2.3 on 2024-06-21 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppingcart',
            old_name='author',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='author',
        ),
        migrations.AddField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='favorite', to='users.customuser', verbose_name='Пользователь'),
            preserve_default=False,
        ),
    ]
