# Generated by Django 3.2.3 on 2024-07-21 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amountreceptingredients',
            options={'default_related_name': 'amount_ingredients', 'ordering': ('-amount',), 'verbose_name': 'Количество ингредиентов в рецепте', 'verbose_name_plural': 'Количество ингредиентов в рецептах'},
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.CharField(editable=False, max_length=64, verbose_name='Единица измерения'),
        ),
    ]
