# Generated by Django 3.2.3 on 2024-07-15 18:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20240714_1959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amountreceptingredients',
            old_name='ingredients',
            new_name='ingredient',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1)], verbose_name='Время приготовления в минутах'),
        ),
    ]
